apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "pm-test-project"
  description: "PM Test Project"
  annotations:
    github.com/project-slug: paulmowat/pm-test-project
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: "group:default/team-a"
